# -*- coding: utf-8 -*-
"""ASS-6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14QfbFG2x7a0AWv5RY1h8s1g1eubtVTLK
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression  
from sklearn.preprocessing import PolynomialFeatures  

df=pd.read_csv('Position_Salary.csv')
print(df.head());

x=df.iloc[:,1:2].values
y=df.iloc[:,2:].values
print(x)

#Fitting the Linear Regression to the dataset  
lin_regs= LinearRegression()  
lin_regs.fit(x,y)

#Fitting the Polynomial regression to the dataset  
poly_regs= PolynomialFeatures(degree= 2)  
x_poly= poly_regs.fit_transform(x)  
lin_reg_2 =LinearRegression()  
lin_reg_2.fit(x_poly, y)

print(x_poly)

#Visulaizing the result for Linear Regression model  
plt.scatter(x,y,color="blue")  
plt.plot(x,lin_regs.predict(x), color="red")  
plt.title("Bluff detection model(Linear Regression)")  
plt.xlabel("Position Levels")  
plt.ylabel("Salary")  
plt.show()

lin_pred = lin_regs.predict([[6.5]])  
print(lin_pred)

poly_pred = lin_reg_2.predict(poly_regs.fit_transform([[6.5]]))  
print(poly_pred)

#degree =3 
poly_regs= PolynomialFeatures(degree= 3)  
x_poly= poly_regs.fit_transform(x)  
lin_reg_2 =LinearRegression()  
lin_reg_2.fit(x_poly, y) 
plt.scatter(x,y,color="blue")  
plt.plot(x,lin_regs.predict(x), color="red")  
plt.title("Bluff detection model(Linear Regression)")  
plt.xlabel("Position Levels")  
plt.ylabel("Salary")  
plt.show()

#degree =4
poly_regs= PolynomialFeatures(degree= 4)  
x_poly= poly_regs.fit_transform(x)  
lin_reg_2 =LinearRegression()  
lin_reg_2.fit(x_poly, y) 
plt.scatter(x,y,color="blue")  
plt.plot(x,lin_regs.predict(x), color="red")  
plt.title("Bluff detection model(Linear Regression)")  
plt.xlabel("Position Levels")  
plt.ylabel("Salary")  
plt.show()